# This is a basic workflow to help you get started with Actions

name: Snowflake_DEV_Deployments

on:
  push:
    branches:
      - DEV
    paths:
      - 'dbscripts/deploy/**'
  workflow_dispatch:
jobs:	
  Dev_Deploy:
    runs-on: ubuntu-latest
    #runs-on: liquibase-latest
    steps:
    - uses: actions/checkout@v2
#Note the below assumes that a host path or volume is mounted into the container at ./Docker(or action will fail)!!!  
    - name: Run 'Liquibase status' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        #args: --url=${{ secrets.SFDEV_URL }} --username=${{ secrets.SFDEV_USERNAME }} --password=${{ secrets.SFDEV_PASSWORD }} --driver=${{ secrets.SFDEV_DRIVER }} --default-schema-name=${{ secrets.SFDEV_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml status
        args: --url=${{ secrets.SFDEV_URL }} --username=${{ secrets.SF_DEV_USERNAME }} --password=${{ secrets.SFDEV_PASSWORD }} --default-schema-name=${{ secrets.SFDEV_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml status
    - name:  Run 'Liquibase update' in a docker container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SFDEV_URL }} --username=${{ secrets.SFDEV_USERNAME }} --password=${{ secrets.SFDEV_PASSWORD }} --default-schema-name=${{ secrets.SFDEV_SCHEMA }} --changeLogFile=/dbscripts/deploy/MasterChangeLog.xml update
